# Generated by Django 3.0.7 on 2020-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='res',
            field=models.FileField(default='', upload_to='appone/media'),
        ),
    ]
